// PAHAM Database Schema & Relationship Visualizer

import React, { useState } from 'react';
import { Layers, Key, ArrowRight, Table, Hash, FileText } from 'lucide-react';

interface SchemaTable {
  name: string;
  primaryKey: string;
  indices: string[];
  description: string;
  relationships: { target: string; foreignKey: string; relationType: '1:1' | '1:N' | 'N:M' }[];
}

const DB_SCHEMA_METADATA: SchemaTable[] = [
  {
    name: 'profiles',
    primaryKey: 'id',
    indices: ['email', 'grade', 'createdAt'],
    description: 'Canonical student user profile including grade, study goals, streak, and onboarding state.',
    relationships: [
      { target: 'studyPlans', foreignKey: 'userId', relationType: '1:N' },
      { target: 'goals', foreignKey: 'userId', relationType: '1:N' },
    ],
  },
  {
    name: 'subjects',
    primaryKey: 'id',
    indices: ['code', 'name', 'curriculum', 'grade'],
    description: 'Indonesian standard curriculum subjects (17 national subjects).',
    relationships: [
      { target: 'chapters', foreignKey: 'subjectId', relationType: '1:N' },
      { target: 'materials', foreignKey: 'subjectId', relationType: '1:N' },
    ],
  },
  {
    name: 'chapters',
    primaryKey: 'id',
    indices: ['subjectId', 'title', 'orderIndex'],
    description: 'Curriculum chapters grouping related learning concepts.',
    relationships: [
      { target: 'concepts', foreignKey: 'chapterId', relationType: '1:N' },
    ],
  },
  {
    name: 'materials',
    primaryKey: 'id',
    indices: ['subjectId', 'title', 'sourceType', 'createdAt'],
    description: 'Scanned teacher notes, uploaded PDFs, or generated summaries.',
    relationships: [
      { target: 'concepts', foreignKey: 'sources[].materialId', relationType: '1:N' },
    ],
  },
  {
    name: 'concepts',
    primaryKey: 'id',
    indices: ['subjectId', 'chapterId', 'title', 'difficultyLevel'],
    description: 'Core atomic learning concepts and Feynman knowledge definitions.',
    relationships: [
      { target: 'studentConceptStates', foreignKey: 'conceptId', relationType: '1:1' },
      { target: 'flashcards', foreignKey: 'conceptId', relationType: '1:N' },
      { target: 'questions', foreignKey: 'conceptId', relationType: '1:N' },
    ],
  },
  {
    name: 'studentConceptStates',
    primaryKey: 'conceptId',
    indices: ['status', 'confidenceLevel', 'lastReviewedAt', 'retentionScore'],
    description: 'Individual student mastery state, confidence level, and FSRS memory card.',
    relationships: [],
  },
  {
    name: 'flashcards',
    primaryKey: 'id',
    indices: ['conceptId', 'subjectId', 'due'],
    description: 'Spaced repetition flashcards with front prompt, back answer, and FSRS interval.',
    relationships: [],
  },
  {
    name: 'questions',
    primaryKey: 'id',
    indices: ['conceptId', 'subjectId', 'difficulty', 'type'],
    description: 'Adaptive multiple-choice and conceptual verification questions.',
    relationships: [
      { target: 'mistakeRecords', foreignKey: 'questionId', relationType: '1:N' },
    ],
  },
  {
    name: 'exams',
    primaryKey: 'id',
    indices: ['examDate', 'targetScore', 'createdAt'],
    description: 'Scheduled school exams (PAS, PTS, UTBK) with target deadlines.',
    relationships: [
      { target: 'examAttempts', foreignKey: 'examId', relationType: '1:N' },
    ],
  },
  {
    name: 'mistakeRecords',
    primaryKey: 'id',
    indices: ['questionId', 'conceptId', 'timestamp', 'reviewed'],
    description: 'Logs of student incorrect answers for AI misconception analysis.',
    relationships: [],
  },
  {
    name: 'learningEvents',
    primaryKey: 'id',
    indices: ['timestamp', 'eventType', 'conceptId'],
    description: 'Chronological telemetry stream of all learning interactions.',
    relationships: [],
  },
  {
    name: 'recommendations',
    primaryKey: 'id',
    indices: ['ruleId', 'priority', 'status', 'createdAt'],
    description: 'Deterministic suggestions generated by Piko Personal Learning Companion.',
    relationships: [],
  },
];

export const DatabaseSchemaView: React.FC = () => {
  const [selectedTable, setSelectedTable] = useState<SchemaTable>(DB_SCHEMA_METADATA[0]);

  return (
    <div className="space-y-6 text-zinc-200 font-mono">
      
      {/* Schema Header */}
      <div className="p-5 rounded-xl bg-zinc-900 border border-zinc-800">
        <h2 className="text-sm font-bold text-zinc-100 flex items-center gap-2">
          <Layers className="w-4 h-4 text-emerald-400" />
          PAHAM Relational & Document Schema Graph
        </h2>
        <p className="text-xs text-zinc-400 mt-1">
          Visual inspection of IndexedDB table schemas, primary keys, indices, and domain relationships.
        </p>
      </div>

      {/* Relational Flow Diagram */}
      <div className="p-5 rounded-xl bg-zinc-950 border border-zinc-800 overflow-x-auto">
        <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block mb-3">
          Core Entity Relationship Flow
        </span>
        <div className="flex items-center gap-3 min-w-[750px] py-2 text-xs">
          <div className="p-3 rounded-lg bg-zinc-900 border border-blue-500/50 text-blue-300 font-bold shadow-lg">
            Profile (User)
          </div>
          <ArrowRight className="w-4 h-4 text-zinc-600 shrink-0" />
          <div className="p-3 rounded-lg bg-zinc-900 border border-emerald-500/50 text-emerald-300 font-bold shadow-lg">
            Subjects (17 Mapel)
          </div>
          <ArrowRight className="w-4 h-4 text-zinc-600 shrink-0" />
          <div className="p-3 rounded-lg bg-zinc-900 border border-emerald-500/50 text-emerald-300 font-bold shadow-lg">
            Chapters & Materials
          </div>
          <ArrowRight className="w-4 h-4 text-zinc-600 shrink-0" />
          <div className="p-3 rounded-lg bg-zinc-900 border border-purple-500/50 text-purple-300 font-bold shadow-lg">
            Concepts (Atomic Unit)
          </div>
          <ArrowRight className="w-4 h-4 text-zinc-600 shrink-0" />
          <div className="p-3 rounded-lg bg-zinc-900 border border-amber-500/50 text-amber-300 font-bold shadow-lg">
            Flashcards & Questions
          </div>
        </div>
      </div>

      {/* Grid: Table Selector + Schema Inspector */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Table Selector */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 space-y-1.5 max-h-[500px] overflow-y-auto">
          <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block mb-2">
            Schema Entities ({DB_SCHEMA_METADATA.length})
          </span>
          {DB_SCHEMA_METADATA.map(tab => (
            <button
              key={tab.name}
              onClick={() => setSelectedTable(tab)}
              className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs transition text-left ${
                selectedTable.name === tab.name
                  ? 'bg-emerald-600/20 text-emerald-300 border border-emerald-500/40 font-bold'
                  : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200'
              }`}
            >
              <span>{tab.name}</span>
              <span className="text-[10px] text-zinc-500">{tab.indices.length} idx</span>
            </button>
          ))}
        </div>

        {/* Selected Schema Detailed Card */}
        <div className="lg:col-span-2 bg-zinc-900 border border-zinc-800 rounded-xl p-5 space-y-5">
          <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
            <div>
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <Table className="w-4 h-4 text-emerald-400" />
                Table: {selectedTable.name}
              </h3>
              <p className="text-xs text-zinc-400 mt-0.5">{selectedTable.description}</p>
            </div>
            <span className="px-2 py-0.5 rounded text-[10px] bg-zinc-800 text-zinc-300">
              Primary Key: <strong>{selectedTable.primaryKey}</strong>
            </span>
          </div>

          {/* Primary Key & Indexes */}
          <div className="space-y-2">
            <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">
              Indexed Columns & Constraints
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              <div className="p-2.5 rounded bg-zinc-950 border border-zinc-800 flex items-center gap-2 text-xs">
                <Key className="w-3.5 h-3.5 text-amber-400" />
                <span>{selectedTable.primaryKey} <strong className="text-amber-400">(PK)</strong></span>
              </div>
              {selectedTable.indices.map(idx => (
                <div key={idx} className="p-2.5 rounded bg-zinc-950 border border-zinc-800 flex items-center gap-2 text-xs">
                  <Hash className="w-3.5 h-3.5 text-blue-400" />
                  <span className="text-zinc-300">{idx}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Relationships */}
          <div className="space-y-2">
            <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">
              Outgoing Relationships
            </span>
            {selectedTable.relationships.length > 0 ? (
              <div className="space-y-2">
                {selectedTable.relationships.map((rel, idx) => (
                  <div key={idx} className="p-3 rounded bg-zinc-950 border border-zinc-800/80 flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="text-emerald-400 font-bold">{selectedTable.name}</span>
                      <ArrowRight className="w-3.5 h-3.5 text-zinc-500" />
                      <span className="text-blue-400 font-bold">{rel.target}</span>
                    </div>
                    <div className="flex items-center gap-2 text-[10px] text-zinc-400">
                      <span>FK: <strong>{rel.foreignKey}</strong></span>
                      <span className="px-1.5 py-0.2 rounded bg-zinc-800 text-zinc-300 font-bold">{rel.relationType}</span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-xs text-zinc-500 italic bg-zinc-950 p-3 rounded">
                Leaf entity or standalone state record (no downstream foreign keys).
              </p>
            )}
          </div>

        </div>

      </div>

    </div>
  );
};
